### PR TITLE
chore: add machine settings to gitignore

### PR DESCRIPTION
**Pull request by koenmetsu**

### CODE REVIEW

**Comment by koenmetsu** [comment]
I think we can use `appsettings.*.json` in `.gitignore` in the future, but wanted to wait until we have decided about `appsettings.DockerDevelopment.json`.

**Comment by koenmetsu** [comment]
Migration re-initialization will be added in another PR, after we have created the `RoadRegistry.Product.ProjectionHost` csproj.

**Comment by yreynhout** [comment]
@koenmetsu settled on `appsettings.development.json` which lands in this PR #17

**Comment by CumpsD** [comment]
If you do `appsettings.*.json` in `.gitignore` don't forget to do `!appsettings.development.json` to exclude it, since people need it after cloning to run the docker compose then

**Pull request merged**
