### PR TITLE
chore: move log level to docker compose - clean up settings

### PR DESCRIPTION
**Pull request by yreynhout**
This PR adjusts the log level of RoadRegistry back to Warning in the production case and moves it to Debug level in the docker composed development case. Removed all the blob client related values and default connection strings in the process (it doesn't make sense to let those bleed into the production images) from `appsettings.json` and moved the majority of those to `appsettings.development.json` instead.

### CODE REVIEW

**Comment by koenmetsu** [comment]
How about leaving them in an appsettings.development.json for easier local dev?

**Comment by yreynhout** [comment]
I'd prefer it to be part of `appsettings.DockerDevelopment.json` and setting the `ASPNETCORE_DEVELOPMENT` to `DockerDevelopment` in the docker-compose file instead. If you want truely local settings, use your machine name - otherwise we run the risk of shipping garbage to production.

**Comment by koenmetsu** [comment]
How is that any different in terms of risk, both are `appsettings.<env>.json` ?

That being said, `appsettings.DockerDevelopment.json` works for me.

**Comment by yreynhout** [comment]
It's different in the sense that `appsettings.DockerDevelopment.json` can be reviewed with less scrutiny than `appsettings.json` (which represents the baseline of things that are the same in any environment). `appsettings.DockerDevelopment.json` will never be executed in production environments, and doesn't event have to be shipped to such an environment (though not very practical).

**Comment by yreynhout** [comment]
There's an aspect of human error in the `appsettings.json` file that I'm not comfortable with (even the base line is somewhat dubious). In that sense if everything was represented in the AWS infrastructure, there would not even be a need for these settings to be shipped (this would be an alternative approach).

**Comment by CumpsD** [comment]
I am very much in favor of having them all in the aws infra configs. I've been trying to move more of them into it, but it is a habit we only picked up late in development.

**Comment by CumpsD** [comment]
> It's different in the sense that `appsettings.DockerDevelopment.json` can be reviewed with less scrutiny than `appsettings.json` (which represents the baseline of things that are the same in any environment). `appsettings.DockerDevelopment.json` will never be executed in production environments, and doesn't event have to be shipped to such an environment (though not very practical).

I think @koenmetsu meant how is `appsettings.DockerDevelopment.json` different from `appsettings.Development.json`

**Comment by yreynhout** [comment]
Oh, there is no difference between those - true that.

**Pull request merged**
